anchor_version = "0.28.0"

[workspace]
members = [
#    "common",
    "programs/maven-jobs",
    "programs/maven-pools",
    "programs/maven-rewards",
    "programs/maven-staking",
    "programs/maven-nodes",
]

[features]
seeds = false
skip-lint = false

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "npm run test"

[test]
startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/programs/mpl_token_metadata.so"

[programs.localnet]
maven_jobs = "nosJTmGQxvwXy23vng5UjkTbfv91Bzf9jEuro78dAGR"
maven_pools = "nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD"
maven_rewards = "nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp"
maven_staking = "nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"
maven_nodes = "nosNeZR64wiEhQc5j251bsP4WqDabT6hmz4PHyoHLGD"

[programs.devnet]
maven_jobs = "nosJTmGQxvwXy23vng5UjkTbfv91Bzf9jEuro78dAGR"
maven_pools = "nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD"
maven_rewards = "nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp"
maven_staking = "nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"
maven_nodes = "nosNeZR64wiEhQc5j251bsP4WqDabT6hmz4PHyoHLGD"

[programs.mainnet]
maven_jobs = "nosJhNRqr2bc9g1nfGDcXXTXvYUmxD4cVwy2pMWhrYM"
maven_pools = "nosPdZrfDzND1LAR28FLMDEATUPK53K8xbRBXAirevD"
maven_rewards = "nosRB8DUV67oLNrL45bo2pFLrmsWPiewe2Lk2DRNYCp"
maven_staking = "nosScmHY2uR24Zh751PmGj9ww9QRNHewh9H59AfrTJE"
maven_nodes = "nosNeZR64wiEhQc5j251bsP4WqDabT6hmz4PHyoHLGD"
